version: "3.7"

services:
  api:
    image: gaeddal-api
    build: .
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=gaeddal
      - DB_HOST=database
    links:
      - database

  database:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=gaeddal
      - DB_HOST=database
    volumes:
      - ~/database/gaeddal:/var/lib/mysql
