version: "3.7"

services:
  api:
    build: .
    restart: always
    env_file:
      - .env
    links:
      - database

  database:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - ~/database/gaeddal:/var/lib/mysql
